### ISSUE TITLE
Build error: Missing header file

### ISSUE THREAD

**Issue by raghavvs** [ChirikjianLab/hrm#2]
In `/hrm/include/hrm/datastructure/DataType.h:26:33:` error: implicit instantiation of undefined template `std::vector<Eigen::Matrix<double, -1, -1, 0>>`

**Comment by ruansp** [comment]
Thanks for pointing out. This happens when you build within docker container or in a local host?

**Comment by raghavvs** [comment]
Local host. I was able to fix this by adding this header file `#include <vector>` to `/hrm/include/hrm/datastructure/DataType.h`
